### ISSUE TITLE
Can't click out of overflow menu.

### ISSUE THREAD

**Issue by ocdtrekkie** [zombiezen/filedrop#1]
If you click on one of the Download/Delete dot menu thingies, you cannot click off of it. You must click Download or Delete or, like, close the tab.

**Comment by zombiezen** [comment]
Looks like [Angular Material issue #3773](https://github.com/angular/material/issues/3773).  It seems to be particular to browser.  I'll try updating the vendored dep and seeing if that fixes it.

**Comment by zombiezen** [comment]
And for reference, can I get your browser/version/OS?

**Comment by ocdtrekkie** [comment]
Windows/Firefox, so yeah 3773 sounds likely.
