### ISSUE TITLE
List of files unavailable.

### ISSUE THREAD

**Issue by ocdtrekkie** [zombiezen/filedrop#2]
I created a grain, dragged two files into it, that all works.
Close grain.
Open grain, and get "List of files unavailable. Retry?"

Tried it again with another file, same result.

**Comment by kentonv** [comment]
Yeah I see this too. Downloading a backup indicates the files are still there, but the files themselves are the only thing that appears to be stored in the grain storage. (Though that seems like it should be enough...)

**Comment by zombiezen** [comment]
Can't reproduce this here... can you paste in the output from the debug log and the JS console?

**Comment by zombiezen** [comment]
(And yes, the file listing comes from listing a directory.  No other metadata.)

**Comment by ocdtrekkie** [comment]
`"Error: this.getFileUrl_ is not a function
filedrop.Files.prototype.list/<@https://alpha-d6s0mcd6hruxyax6pql5.sandstorm.io/bundle.js:777:18
f/<@https://alpha-d6s0mcd6hruxyax6pql5.sandstorm.io/bundle.js:112:20
Pe/this.$get</l.prototype.$eval@https://alpha-d6s0mcd6hruxyax6pql5.sandstorm.io/bundle.js:125:301
Pe/this.$get</l.prototype.$digest@https://alpha-d6s0mcd6hruxyax6pql5.sandstorm.io/bundle.js:122:390
Pe/this.$get</l.prototype.$apply@https://alpha-d6s0mcd6hruxyax6pql5.sandstorm.io/bundle.js:126:56
l@https://alpha-d6s0mcd6hruxyax6pql5.sandstorm.io/bundle.js:81:169
P@https://alpha-d6s0mcd6hruxyax6pql5.sandstorm.io/bundle.js:85:301
vf/</w.onload@https://alpha-d6s0mcd6hruxyax6pql5.sandstorm.io/bundle.js:86:315
"`

There is nothing valuable in the debug log, my console error is above. (Sorry I forgot to check here when I filed the bug.)
